name: 02 Frontend Build

on:
  workflow_run:
    workflows:
      - 01 Code Quality Check
    types:
      - completed

jobs:
  frontend-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm ci

      - name: Build Frontend
        run: |
          cd client
          npm run build
