name: 06 Deploy Production

on:
  workflow_run:
    workflows:
      - 04 Security Audit
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm ci

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Deploy Frontend to Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./client/dist/
          server-dir: ./dmifotech.com/

      - name: Deploy Backend to Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./server/
          server-dir: ./api.dmifotech.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
